pipeline {
	agent {
		docker {
			image 'bitnami/dotnet-sdk'
			args '-u vatencio:Test1234!'
		}
	}

    environment {
        DOTNET_CLI_HOME = 'C:\\Program Files\\dotnet'
		DOCKER_HOST = 'tcp://localhost:2375'
    }

    stages {
		stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
					//permissions
					sh 'chmod +x docker'
					
                    // Restoring dependencies
                    //bat "cd ${DOTNET_CLI_HOME} && dotnet restore"
                    sh 'cd ${DOTNET_CLI_HOME} && dotnet restore'

                    // Building the application
                    sh 'dotnet build --configuration Release'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Running tests
                    sh 'dotnet test --no-restore --configuration Release'
                }
            }
        }

        stage('Publish') {
            steps {
                script {
                    // Publishing the application
                    sh 'dotnet publish --no-restore --configuration Release --output .\\publish'
                }
            }
        }
    }

    post {
        success {
            echo 'Build, test, and publish successful!'
        }
    }
}