pipeline {
	agent {
		docker {
			image 'bitnami/dotnet-sdk'
		}
	}

    environment {
        DOTNET_CLI_HOME = 'C:\\Program Files\\dotnet'
		DOCKER_HOST = 'tcp://localhost:2375'
    }



    post {
        success {
            echo 'Build, test, and publish successful!'
        }
    }
}